title: "ClimSim"
description: >
  "Analysis-ready optimized ClimSim data"
recipes:
  - id: "climsim-lowres-mli"
    object: "recipe:climsim_lowres_mli"
  - id: "climsim-lowres-mlo"
    object: "recipe:climsim_lowres_mlo"
provenance:
  providers:
    - name: "Hugging Face"
      description: "Hugging Face"
      roles:
        - host
      url: https://huggingface.co/datasets/LEAP/ClimSim_low-res
    - name: "Sungduk Yu et al"
      description: "ClimSim: An open large-scale dataset for training high-resolution physics emulators in hybrid multi-scale climate simulators"
      roles:
        - producer
        - licensor
      url: https://arxiv.org/abs/2306.08754
  license: "Apache-2.0"
maintainers:
  - name: "Qingyuan Yang"
    orcid: "https://orcid.org/0000-0002-5631-889X"
    github: yiqioyang
  - name: "Julius Busecke"
    orcid: "https://orcid.org/0000-0001-8571-865X"
    github: jbusecke
